site_name: TephrocactusMYC's CTF WP
site_url: https://tephrocactusmyc.github.io/CTF-CLASS/
site_author: TephrocactusMYC
site_description: >-
  我的 CTF 之路

repo_name: CTF-CLASS
repo_url: https://github.com/TephrocactusMYC/CTF-CLASS/

copyright: Copyright &copy; 2023-present <a href="https://github.com/TephrocactusMYC" target="_blank" rel="noopener noreferrer">TephrocactusMYC</a>

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  favicon: images/favicon.ico
  apple-touch-icon-precomposed: images/mobile_icon.png
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    # - navigation.instant
    # - navigation.expand
    # - navigation.sections
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

  custom_dir: overrides

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes

plugins:
  - i18n:
      default_language: zh
      material_alternate: true
      languages:
        zh:
          name: 简体中文
          build: true
        en:
          name: English
          build: true
          site_name: A WEBSITE ABOUT MY CTF WP
  - search:
      lang: ja
  - git-revision-date-localized
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://tephrocactusmyc.github.io/CTF-CLASS/
  analytics:
    provider: google
    property: G-KJB4RXSKZG

nav:
  - ABOUT: "README.md"
  - CSE365:
      - ABOUT CSE365: "CSE365/README.md"
      - talking-web: "CSE365/talking-web.md"
      - cryptography: "CSE365/cryptography.md"
      - websecurity: "CSE365/websecurity.md"
  - CSE466:
      - ABOUT CSE466: "CSE466/README.md"
      - program misuse: "CSE466/program-misuse.md"
      - program interaction: "CSE466/program-interaction.md"
  - WarGame:
      - ABOUT WarGame: "WarGame/REAMD.md"
      - bandit: "WarGame/bandit.md"
      - krypton: "WarGame/krypton.md"
      - leviathan: "WarGame/leviathan.md"
      - natas: "WarGame/Natas.md"
  -MalwareAnalysis:
      - ABOUT MalwareAnalysis: "MalwareAnalysis/READMD.md"
      - knoweledge:
        - ch0: "MalwareAnalysis/knowledge/ch0.md"
        - ch1: "MalwareAnalysis/knowledge/ch1.md"
      - Lab:
        - lab1: "MalwareAnalysis/Lab/lab1.md"

